Repository ManageIQ/activerecord-virtual_attributes, pull requests merged in 2022-01, with the labels that each got.

#98 Using actions instead of travis ci
  .github/workflows/ci.yml
  .travis.yml
  README.md
Labels: developer

#100 Update GitHub actions for consistency
  .github/workflows/ci.yaml
  .github/workflows/ci.yml
  README.md
  activerecord-virtual_attributes.gemspec
  spec/db/database.yml
Labels: test

#97 Rails 5.2 changes (many needed for 6.1 support)
  activerecord-virtual_attributes.gemspec
  lib/active_record/virtual_attributes/virtual_delegates.rb
  lib/active_record/virtual_attributes/virtual_fields.rb
  lib/active_record/virtual_attributes/virtual_total.rb
  spec/virtual_attributes_spec.rb
  spec/virtual_includes_spec.rb
Labels: cleanup

#103 Auto add grouping
  lib/active_record/virtual_attributes/virtual_arel.rb
  spec/db/models.rb
  spec/virtual_attributes_spec.rb
Labels: enhancement, rails6.1
