Repository ManageIQ/activerecord-virtual_attributes, pull requests merged in 2022-02, with the labels that each got.

#101 Rails6.1
  .github/workflows/ci.yaml
  CHANGELOG.md
  Gemfile
  gemfiles/gemfile_61.gemfile
  lib/active_record/virtual_attributes/virtual_arel.rb
  lib/active_record/virtual_attributes/virtual_delegates.rb
  lib/active_record/virtual_attributes/virtual_fields.rb
  lib/active_record/virtual_attributes/virtual_total.rb
  spec/db/database.yml
  spec/support/database.rb
  spec/virtual_attributes_spec.rb
  spec/virtual_delegates_spec.rb
  spec/virtual_includes_spec.rb
  spec/virtual_total_spec.rb
Labels: enhancement, rails6.1

#105 Drop rails 5.2 support
  .github/workflows/ci.yaml
  Appraisals
  gemfiles/gemfile_52.gemfile
  lib/active_record/virtual_attributes.rb
  lib/active_record/virtual_attributes/arel_groups.rb
  lib/active_record/virtual_attributes/virtual_fields.rb
Labels: enhancement, rails6.1

#106 Drop rails 6.0 support
  .github/workflows/ci.yaml
  Appraisals
  Gemfile
  activerecord-virtual_attributes.gemspec
  gemfiles/gemfile_60.gemfile
  gemfiles/gemfile_61.gemfile
  lib/active_record/virtual_attributes/virtual_arel.rb
  lib/active_record/virtual_attributes/virtual_fields.rb
  spec/support/database.rb
  spec/virtual_attributes_spec.rb
Labels: enhancement, rails6.1

#107 Move versioning verbiage into README
  CHANGELOG.md
  README.md
Labels: documentation

#108 Cleanup for consistency
  .github/workflows/ci.yaml
Labels: cleanup

#109 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: test, developer
