Repository ManageIQ/activerecord-virtual_attributes, pull requests merged in 2023-06, with the labels that each got.

#122 support bind variables in virtual delegate reflections
  lib/active_record/virtual_attributes/virtual_delegates.rb
  spec/db/models.rb
  spec/db/schema.rb
  spec/virtual_delegates_spec.rb
Labels: bug

#123 Support virtual_totals for habtm
  lib/active_record/virtual_attributes/virtual_total.rb
  spec/db/models.rb
  spec/virtual_total_spec.rb
Labels: enhancement

#120 Handle 'uses' delegating to another 'uses' that has a deep hash
  lib/active_record/virtual_attributes/virtual_fields.rb
  spec/db/models.rb
  spec/virtual_includes_spec.rb
Labels: bug

#129 Add Ruby 3.0 to CI
  .github/workflows/ci.yaml
Labels: test
