Repository ManageIQ/activerecord-virtual_attributes, pull requests merged in 2024-07, with the labels that each got.

#148 fix bin/console
  bin/console
  spec/support/database.rb
Labels: bug, developer

#146 Rails 7 mvp (just get it runnable with rails 7)
  activerecord-virtual_attributes.gemspec
  lib/active_record/virtual_attributes/virtual_fields.rb
Labels: enhancement

#152 drop virtual_aggregate
  lib/active_record/virtual_attributes/virtual_total.rb
Labels: technical debt

#151 Resolve rubocops
  activerecord-virtual_attributes.gemspec
  bin/console
  lib/active_record/virtual_attributes/rspec/have_virtual_attribute.rb
  lib/active_record/virtual_attributes/virtual_delegates.rb
  lib/active_record/virtual_attributes/virtual_fields.rb
  lib/active_record/virtual_attributes/virtual_reflections.rb
  lib/active_record/virtual_attributes/virtual_total.rb
  seed.rb
  spec/support/byebug.rb
  spec/support/database.rb
  spec/support/with_test_class.rb
  spec/virtual_attributes_spec.rb
  spec/virtual_delegates_spec.rb
  spec/virtual_includes_spec.rb
  spec/virtual_total_spec.rb
Labels: technical debt

#153 Drop attributes_builder
  lib/active_record/virtual_attributes.rb
Labels: technical debt

#154 Use Arel.sql shortcut for sql literals
  lib/active_record/virtual_attributes/virtual_total.rb
Labels: refactoring

#156 Document that in 7.1, this monkey patch is no longer needed
  lib/active_record/virtual_attributes/virtual_arel.rb
Labels: cleanup

#149 replace_virtual_field condenses returning includes
  lib/active_record/virtual_attributes/virtual_fields.rb
  spec/virtual_attributes_spec.rb
  spec/virtual_includes_spec.rb
Labels: enhancement, rails7

#157 Order specs
  spec/virtual_attributes_spec.rb
Labels: test

#114 Introduce Arel::Nodes::VirtualAttribute
  lib/active_record/virtual_attributes/virtual_arel.rb
  lib/active_record/virtual_attributes/virtual_delegates.rb
  lib/active_record/virtual_attributes/virtual_fields.rb
  lib/active_record/virtual_attributes/virtual_total.rb
Labels: enhancement

#150 Add rails 7.0 support and drop rails 6.1
  CHANGELOG.md
  Gemfile
  activerecord-virtual_attributes.gemspec
  lib/active_record/virtual_attributes/version.rb
  lib/active_record/virtual_attributes/virtual_fields.rb
  spec/spec_helper.rb
  spec/virtual_includes_spec.rb
Labels: enhancement, rails7
