Repository ManageIQ/activerecord-virtual_attributes, pull requests merged in 2025-02, with the labels that each got.

#175 Bump manageiq-style for rexml CVEs
  activerecord-virtual_attributes.gemspec
Labels: dependencies

#168 Rails 7.1 support
  .github/workflows/ci.yaml
  Gemfile
  lib/active_record/virtual_attributes/virtual_delegates.rb
Labels: enhancement, rails7.1

#178 version 7.1 changelog
  CHANGELOG.md
Labels: documentation, rails7.1

#177 Add tests for delegations to same model
  spec/db/models.rb
  spec/db/schema.rb
  spec/virtual_delegates_spec.rb
Labels: test
